const conf = {
    appwriteUrl:String(process.env.NEXT_PUBLIC_APPWRITE_URL),
    appwriteProjectId:String(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID),
    appwriteDatabaseId:String(process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID),
    
    appwriteModalCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_MODAL_COLLECTION_ID),
    appwriteHeroBannerCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_HEROBANNER_COLLECTION_ID), 
    appwriteInfrastructureCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_INFRASTRUCTURE_COLLECTION_ID), 
    appwritePreviousYearPaperCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_PREVIOUSYEARPAPER_COLLECTION_ID),
    appwriteEventsCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID),
    appwriteAcademicUpdateCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_ACADEMICUPDATE_COLLECTION_ID),
    appwriteSubjectCollectionId:String(process.env.NEXT_PUBLIC_APPWRITE_SUBJECT_COLLECTION_ID),
    appwriteTeacherCareId:String(process.env.NEXT_PUBLIC_APPWRITE_TEACHER_CARE_ID),
    appwriteStudentEnrichmentId:String(process.env.NEXT_PUBLIC_APPWRITE_STUDENT_ENRICHMENT_ID),
    appwriteAtlCornerId:String(process.env.NEXT_PUBLIC_APPWRITE_ATL_CORNER_ID),
    appwriteCommunityOutreachId:String(process.env.NEXT_PUBLIC_APPWRITE_COMMUNITY_OUTREACH_ID),
    appwriteNewsLetterId:String(process.env.NEXT_PUBLIC_APPWRITE_NEWS_LETTER_ID),
    appwriteCalendarId:String(process.env.NEXT_PUBLIC_APPWRITE_CALENDAR_ID),
    appwriteNationalAndInternationalId:String(process.env.NEXT_PUBLIC_APPWRITE_NATIONAL_AND_INTERNATIONAL_ID),
    appwriteCampusHappeningId:String(process.env.NEXT_PUBLIC_APPWRITE_CAMPUS_HAPPENING_ID),
    appwriteGalleryId:String(process.env.NEXT_PUBLIC_APPWRITE_GALLERY_ID),
    appwriteGalleryVideoId:String(process.env.NEXT_PUBLIC_APPWRITE_GALLERY_VIDEO_ID),
    appwriteNkbgsFamilyId:String(process.env.NEXT_PUBLIC_APPWRITE_NKBGS_FAMILY_ID),
    appwriteCbseResultClassXId:String(process.env.NEXT_PUBLIC_APPWRITE_CBSE_RESULT_CLASS_X_ID),
    appwriteCbseResultClassXIIId:String(process.env.NEXT_PUBLIC_APPWRITE_CBSE_RESULT_CLASS_XII_ID),
    appwriteTopperId:String(process.env.NEXT_PUBLIC_APPWRITE_TOPPER_ID),
    appwriteAchieverId:String(process.env.NEXT_PUBLIC_APPWRITE_ACHIEVER_ID),
    appwriteNinetyId:String(process.env.NEXT_PUBLIC_APPWRITE_NINETY_ID),
    appwriteSubjectWiseId:String(process.env.NEXT_PUBLIC_APPWRITE_SUBJECT_WISE_ID),
    appwriteVacancyId:String(process.env.NEXT_PUBLIC_APPWRITE_VACANCY_ID),
    appwriteProudMomentsId:String(process.env.NEXT_PUBLIC_APPWRITE_PROUD_MOMENTS_ID),
    appwriteSportId:String(process.env.NEXT_PUBLIC_APPWRITE_SPORT_ID),
    appwriteSportDetailId:String(process.env.NEXT_PUBLIC_APPWRITE_SPORT_DETAIL_ID),
    appwriteExcursionsId:String(process.env.NEXT_PUBLIC_APPWRITE_EXCURSIONS_ID),
    appwriteInternationalVisitId:String(process.env.NEXT_PUBLIC_APPWRITE_INTERNATIONALVISIT_ID),
    appwriteValueEducationId:String(process.env.NEXT_PUBLIC_APPWRITE_VALUE_EDUCATION_ID),
    appwriteWorkshopByPrincipalId:String(process.env.NEXT_PUBLIC_APPWRITE_WORKSHOP_BY_PRINCIPAL_ID),
    appwriteSpecialEducationId:String(process.env.NEXT_PUBLIC_APPWRITE_SPECIAL_EDUCATION_ID),
    appwriteClubId:String(process.env.NEXT_PUBLIC_APPWRITE_CLUB_ID),
    appwriteClubDetailId:String(process.env.NEXT_PUBLIC_APPWRITE_CLUB_DETAIL_ID),
    appwriteAdmissionId:String(process.env.NEXT_PUBLIC_APPWRITE_ADMISSION_ID),
    

    appwriteBucketId:String(process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID),
    appwritePdfBucketId:String(process.env.NEXT_PUBLIC_APPWRITE_PDF_BUCKET_ID),
}


export default conf;